server:
  port: 8200
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
    register-with-eureka: true
    fetch-registry: true
spring:
  application:
    name: homeconfig
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhangxw92/cloud-demo.git
          search-paths:
            - home-config
      label: master



