server:
  port: 8002

eureka:
  instance:
    hostname: eurekagateway
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: gateway-service
          uri: https://blog.csdn.net
          predicates:
            - Path=/meteor_93/**

        - id: gateway-service2
          uri: lb://order
          predicates:
            - Path=/hello/**
          #filters: #限流过滤器
          #  - name: RequestRateLimiter
          #    args:
          #      redis-rate-limiter.replenishRate: 1 #令牌桶每秒填充速率
          #      redis-rate-limiter.burstCapacity: 1 #令牌桶总容量
          #      key-resolver: "#{@keyResolver}" #使用spel 表达式按名称引用bean
          filters:
          - name: RequestRateLimiter
            args:
              key-resolver: '#{@ipKeyResolver}'
              redis-rate-limiter.replenishRate: 2
              redis-rate-limiter.burstCapacity: 10
  redis:
    host: 39.102.61.252
    port: 6379
    database: 0
    password:
    lettuce:
      pool:
        max-active: 8 #最大连接数
        max-idle: 8 #最大连接阻塞等待事件
        max-wait: -1 #最大空闲连接
        min-idle: 0 #最小空闲连接
