server:
  port: 8002

eureka:
  instance:
    hostname: eurekagateway
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: gateway-service
          uri: https://blog.csdn.net
          predicates:
            - Path=/meteor_93/**

        - id: gateway-service2
          uri: lb://order
          predicates:
            - Path=/hello/**
  redis:
    host: 39.102.61.252
    port: 6379
    database: 0
    password:
    lettuce:
      pool:
        max-active: 8 #最大连接数
        max-idle: 8 #最大连接阻塞等待事件
        max-wait: -1 #最大空闲连接
        min-idle: 0 #最小空闲连接
