server:
  port: 8002

eureka:
  instance:
    hostname: eurekagateway
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: gateway-service
          uri: https://blog.csdn.net
          predicates:
            - Path=/meteor_93/**

        - id: gateway-service2
          uri: lb://order
          predicates:
            - Path=/hello/**

