
server:
  port: 9001
spring:
  application:
    name: order
eureka:
  instance:
    hostname: order
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka

