server:
  port: 8001

spring:
  application:
    name: home-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称j进行路由
      routes:
       - id: order_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
         #匹配后提供服务的路由地址
         uri: lb://HOME-ORDER
         predicates:
          - Path=/hello # 断言，路径相匹配的进行路由

spring.redis.cl
eureka:
  instance:
    hostname: home-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka/